# Configuration file for sending lunch email messages. This is set up to use
# simple username/password authentication where the password can be a normal
# password or an app password generated for Gmail.

# If different authentication is needed then the program will have to be
# altered along with adding the appropriate configuration items in this file.

# Server connection/login info
server: "smtp.gmail.com"
port: "465"  # SSL
# 'user' contains the login/email name for the user. This item is also used in
# "From:" email line. Gmail uses the same for both.
user: "MY_USER@gmail.com"
# 'pwd' contains a password for the user.
pwd: "MY_GMAIL_APP_PASSWORD"



# 'to' contains a list of email addresses to be used on the 'To' line.
to: 
  - "user1@gmail.com"
  - "user2@comcast.net"

subject: "Lunch Friday"

# 'template' should contain text to be used as a Python template for the
# body of the message. Current values in the dict used are 'date' and 'loc'.
template: |
  All,
  
  Lunch Friday ($date) will be at $loc, 11:15.

  See you there!
  Mike

# 'lunchfile' contains a URI to the file
# E.g., "https://someserveraddress/filelocation" or
# "file:localfilelocation"
lunchfile: "file:/workspaces/LunchPython/lunch.txt"